#!/usr/bin/env bash

blue_color='\x1b[0;34m'
reset_color='\x1b[0m'

if [ $# -ge 1 ]; then
  if [ ! $# -eq 1 ]; then
    echo "I just need one file, but thanks."
  fi
  output=$1
else
  output="$PWD/LICENSE"
fi

printf "Copying to ${blue_color}%s${reset_color}...\n" $output
cp $UTILS_PATH/templates/licenses/CC0 $output
