#!/usr/bin/env bash

blue_color='\x1b[0;34m'
reset_color='\x1b[0m'

if [ $# -eq 1 ]; then
  output=$1
elif [ $# -gt 1 ]; then
  echo "Sorry, I just need one file, but thanks."
  output=$1
else
  output="$PWD/README.md"
fi

printf "Copying to ${blue_color}%s${reset_color}...\n" $output
cp $UTILS_PATH/templates/readmes/CC0.md $output
