#!/usr/bin/env bash

progname=$(basename $0)

blue_color='\x1b[0;34m'
reset_color='\x1b[0m'
TEMPLATES=$UTILS_PATH/templates

function copy() {
  printf "Copying to ${blue_color}%s${reset_color}...\n" $2
  cp $1 $2
}

if [ $# -ge 1 ]; then
  if [ ! $# -eq 1 ]; then
    echo "I just need one file, but thanks."
  fi
  output=$1
else
  case $progname in
    *license) output="$PWD/LICENSE" ;;
    *readme) output="$PWD/Readme.md" ;;
  esac
fi

case $progname in
  mkCC0*) license='CC0' ;;
  mkGPLv2*) license='GPLv2' ;;
  mkGPLv3*) license='GPLv3' ;;
  mkLGPL*) license='LGPL' ;;
  mkMIT*) license='MIT' ;;
  mkBSD2*) license='BSD-2' ;;
  mkBSD3*) license='BSD-3' ;;
  mkApache2*) license='Apache2' ;;
  mkMozilla*) license='Mozilla' ;;
  *) license='CC0'
esac

case $progname in
  *license) filetype='license'; ;;
  *readme) filetype='readme'; ;;
  *) filetype=''
esac

case $filetype in
  license) copy ${TEMPLATES}/licenses/$license $output ;;
  readme) copy ${TEMPLATES}/readmes/$license.md $output ;;
  *) echo "Didn't copy anything."; exit 1
esac
