#!/usr/bin/env bash

FILE=$1
REMOTE=$2
RFILE=$3

function error() {
  printf "Error: %s\n" $1
  exit 1
}

function usage() {
  echo "Usage: "
  echo "~$ $0 <file> <remote-host> <remote-file> [port]"
  echo ""
}

if [ ! $PORT ];then
  if [ $4 ];then
    PORT=$4
  else
    PORT=22
  fi
fi

if [ ! $FILE ];then
  usage
  error "No file to transfer"
elif [ ! $REMOTE ];then
  usage
  error "No host set"
elif [ ! $RFILE ];then
  RFILE='~/'
fi

rsync -avz -e "ssh -p $PORT -o StrictHostKeyChecking=no -o
UserKnownHostsFile=/dev/null" --progress $FILE $REMOTE:$RFILE
